version: '3.8'

services:
  toxic-comment-classifier:
    image: workshop-toxic-comment-classifier:latest
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    volumes:
      - ./container-data:/app
    restart: unless-stopped
